export const styles = {
  container: {
    minHeight: "100vh",
    background: "linear-gradient(to bottom right, #dbeafe, #e0e7ff, #f3e8ff)",
    display: "flex",
  },
  sidebar: {
    width: "280px",
    background: "linear-gradient(to bottom, #1e293b, #334155)",
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  sidebarButton: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 16px",
    background: "transparent",
    border: "none",
    borderRadius: "8px",
    color: "#cbd5e1",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: "500",
    transition: "all 0.2s",
    textAlign: "left",
  },
  sidebarButtonActive: {
    background: "rgba(99, 102, 241, 0.2)",
    color: "#a5b4fc",
  },
  mainContent: {
    flex: 1,
    padding: "32px",
    overflowY: "auto",
  },
  header: {
    marginBottom: "32px",
  },
  headerTitle: {
    fontSize: "32px",
    fontWeight: "bold",
    color: "#111827",
    marginBottom: "8px",
  },
  headerSubtitle: {
    color: "#6b7280",
    fontSize: "16px",
  },
  card: {
    background: "white",
    borderRadius: "16px",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
    padding: "24px",
    marginBottom: "24px",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "20px",
    marginBottom: "32px",
  },
  statCard: {
    background: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  button: {
    padding: "12px 24px",
    background: "linear-gradient(to right, #4f46e5, #7c3aed)",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "15px",
    fontWeight: "600",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s",
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    border: "2px solid #e5e7eb",
    borderRadius: "8px",
    fontSize: "15px",
    outline: "none",
    transition: "all 0.2s",
  },
  textarea: {
    width: "100%",
    height: "120px",
    padding: "12px 16px",
    border: "2px solid #e5e7eb",
    borderRadius: "12px",
    fontSize: "15px",
    outline: "none",
    resize: "none",
    transition: "all 0.2s",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: "12px 16px",
    fontWeight: "600",
    color: "#374151",
    borderBottom: "2px solid #e5e7eb",
    fontSize: "14px",
  },
  td: {
    padding: "12px 16px",
    borderBottom: "1px solid #f3f4f6",
  },
};